version: '3.8'

services:
  web:
    build: .
    ports:
      - "800:80"        # maps Apache inside container to port 800 on host
      - "4434:443"      # optional, if using HTTPS
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bbms
    ports:
      - "3308:3306"     # maps MySQL inside container to 3308 on host
